apiVersion: v1
kind: Pod
metadata:
  name: mnist-train
spec:
  restartPolicy: Never
  containers:
  - name: mnist-train
    image: irenetht/mnist:train
    command: ['sh', '-c', 'python3 main.py --epoch 1']
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"
